### ISSUE TITLE
Not working with chef 13.6.4 on osx

### ISSUE THREAD

**Issue by balazsadam** [pdf/knife-attribute#4]
Hi

bash# chef gem install knife-attribute
Fetching: knife-attribute-1.1.0.gem (100%)
Successfully installed knife-attribute-1.1.0
1 gem installed

bash# knife rehash

bash# knife node attribute get sql-server mariadb

/Users/balazsasd/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/get.rb:4:in `<class:NodeAttributeGet>': uninitialized constant KnifeAttribute::Node::Helpers (NameError)
	from /Users/balazsasd/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/get.rb:3:in `<module:Node>'
	from /Users/balazsasd/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/get.rb:2:in `<module:KnifeAttribute>'
	from /Users/balazsasd/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/get.rb:1:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:80:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:80:in `block in load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:78:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:78:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:255:in `load'
	from /usr/local/bin/knife:255:in `<main>'

bash# chef --version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
bash#

**Comment by balazsadam** [comment]
After installation, more snippets:

bash#  knife node
FATAL: Cannot find subcommand for: 'node'
If this is a recently installed plugin, please run 'knife rehash' to update the subcommands cache.
Available node subcommands: (for details, knife SUB-COMMAND --help)

** NODE COMMANDS **
/Users/balazsasd/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/delete.rb:4:in `<class:NodeAttributeDelete>': uninitialized constant KnifeAttribute::Node::Helpers (NameError)
	from /Users/balazsasd/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/delete.rb:3:in `<module:Node>'
	from /Users/balazsasd/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/delete.rb:2:in `<module:KnifeAttribute>'
	from /Users/balazsasd/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/delete.rb:1:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:80:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:80:in `block in load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:78:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:78:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:246:in `block (2 levels) in list_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:245:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:245:in `block in list_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:242:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:242:in `list_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:273:in `subcommand_not_found!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:255:in `load'
	from /usr/local/bin/knife:255:in `<main>'

**Comment by pdf** [comment]
I've never used `knife rehash`.  Apparently the custom class loader they're using there breaks standard module loading.

If you want the plugin to work in the short term, just delete your `~/.chef/plugin_manifest.json`, but I'll look into how to make this work with their custom loader at some stage.

**Comment by balazsadam** [comment]
I have removed manifest file, it work after! Thanks for help, but i would like to work with knife rehash.

best regards.

**Comment by pdf** [comment]
I have opened an issue against the Chef project to see if they will fix knife rehash to work properly, otherwise, I can change the project structure to make it work.
